name: chat_app
description: A chat application built with Flutter, Firebase, and BLoC pattern for real-time messaging and secure authentication.
version: 1.0.0
environment:
  # Specify the required SDK versions
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase core for initializing Firebase services
  firebase_core: ^3.6.0
  # Firebase Authentication for user sign-in and sign-up
  firebase_auth: ^5.3.1
  # Firestore for real-time database and messaging
  cloud_firestore: ^5.4.4
  # Secure storage for storing user tokens (not used on web)
  flutter_secure_storage: ^9.2.2
  # BLoC for state management
  flutter_bloc: ^8.1.5
  # Equatable for comparing objects in BLoC states/events
  equatable: ^2.0.5
  # Environment variables for secure configuration
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting rules for code quality
  flutter_lints: ^4.0.0

flutter:
  # Enable Material Design
  uses-material-design: true
  assets:
    - .env