# Project metadata
name: chat_app
# Brief description of the project
description: A Flutter-based chat application using Firebase for real-time messaging, Firebase Authentication for secure user management, and BLoC pattern with feature-first architecture for state management and maintainability.
# Version of the app
version: 1.0.0

# Environment constraints
environment:
  # Specifies the Dart SDK version range supported by the project
  sdk: '>=3.0.0 <4.0.0'

# Runtime dependencies required for the app
dependencies:
  flutter:
    # Core Flutter SDK for building the app
    sdk: flutter
  firebase_core: ^3.6.0
    # Firebase Core for initializing Firebase services
  firebase_auth: ^5.3.1
    # Firebase Authentication for user sign-in, sign-up, and session management
  cloud_firestore: ^5.4.4
    # Cloud Firestore for real-time database to store and sync chat messages
  flutter_secure_storage: ^9.2.2
    # Flutter Secure Storage for securely storing user tokens (not used on web platforms)
  flutter_bloc: ^9.0.1
    # Flutter BLoC for state management, handling authentication and chat logic
  equatable: ^2.0.5
    # Equatable for simplifying object comparison in BLoC states and events
  flutter_dotenv: ^5.1.0
    # Flutter Dotenv for loading environment variables from .env file (e.g., Firebase API keys)
  flex_color_scheme: ^8.2.0
    # Flex Color Scheme for advanced theming, used for Dribbble-inspired UI with light/dark modes
  get_it: ^7.7.0
    # GetIt for dependency injection to manage repository and data source instances
  dartz: ^0.10.1
    # Dartz for functional programming utilities (e.g., Either for error handling)

# Development dependencies used for testing and linting
dev_dependencies:
  flutter_test:
    # Flutter testing framework for unit and widget tests
    sdk: flutter
  flutter_lints: ^4.0.0
    # Flutter Lints for enforcing code quality and best practices

# Flutter-specific configurations
flutter:
  # Enables Material Design components for consistent UI
  uses-material-design: true
  # Assets included in the app, such as configuration files
  assets:
    # Environment file for Firebase configuration
    - .env